kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: gold
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Mi