# WARNING: deprecated due to the mount error.
# using local storage in minikube environment
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  namespace: gold
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: cpuguy83/nfs-server
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          args:
            # Pass the paths to share to the Docker image
            - /exports
          volumeMounts:
            - mountPath: /exports
              name: mypvc
      volumes:
        - name: mypvc
          hostPath:
            path: /mnt/default
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: gold
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server