apiVersion: v1
kind: Service
metadata:
  name: gold-redis
  namespace: gold
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend