apiVersion: v1
kind: Service
metadata:
  name: mongo-restful
  namespace: gold
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
